# Copyright Contributors to the Open Cluster Management project
# Licensed under the Apache License 2.0

FROM registry.redhat.io/openshift/golang-builder:golang-builder-v1.25-rhel9 AS builder

WORKDIR /workspace
COPY . .

RUN go mod vendor
RUN GOFLAGS="" CGO_ENABLED=1 go build -o operator ./cmd/operator/

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=builder /workspace/operator /bin/operator

USER nobody

ENTRYPOINT ["/bin/operator"]

LABEL com.redhat.component="prometheus-operator" \
  name="prometheus-operator" \
  summary="prometheus-operator" \
  io.openshift.expose-services="" \
  io.openshift.tags="data,images" \
  io.k8s.display-name="prometheus-operator" \
  maintainer="" \
  description="prometheus-operator" \
  io.k8s.description="prometheus-operator"
