# Copyright Contributors to the Open Cluster Management project
# Licensed under the Apache License 2.0

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.25 AS builder

WORKDIR /workspace
COPY . .

RUN go mod vendor
RUN CGO_ENABLED=1 go build -o prometheus-config-reloader ./cmd/prometheus-config-reloader/

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=builder /workspace/prometheus-config-reloader /bin/prometheus-config-reloader

USER nobody

ENTRYPOINT ["/bin/prometheus-config-reloader"]

LABEL com.redhat.component="prometheus-config-reloader" \
  name="rhacm2/acm-prometheus-config-reloader-rhel9" \
  cpe="cpe:/a:redhat:acm:2.16::el9" \
  summary="prometheus-config-reloader" \
  io.openshift.expose-services="" \
  io.openshift.tags="data,images" \
  io.k8s.display-name="prometheus-config-reloader" \
  maintainer="" \
  description="prometheus-config-reloader" \
  io.k8s.description="prometheus-config-reloader"
