# Copyright Contributors to the Open Cluster Management project
# Licensed under the Apache License 2.0

FROM registry.ci.openshift.org/stolostron/builder:go1.25-linux AS builder

WORKDIR /workspace
COPY . .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o prometheus-config-reloader ./cmd/prometheus-config-reloader/

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=builder /workspace/prometheus-config-reloader /bin/prometheus-config-reloader

USER 1001

ENTRYPOINT ["/bin/prometheus-config-reloader"]
